// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAtWAWZja0_cHR3J1DANJ_43c1unR5jhI',
    appId: '1:422614900421:web:24e3511683ea0f6c679aac',
    messagingSenderId: '422614900421',
    projectId: 'crud-1a5f7',
    authDomain: 'crud-1a5f7.firebaseapp.com',
    storageBucket: 'crud-1a5f7.firebasestorage.app',
    measurementId: 'G-71CT2P8YH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHASVKZDZDsn5wC5XnyTdbVo7nfSzoxns',
    appId: '1:422614900421:android:a30de95a2db6e403679aac',
    messagingSenderId: '422614900421',
    projectId: 'crud-1a5f7',
    storageBucket: 'crud-1a5f7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAtWAWZja0_cHR3J1DANJ_43c1unR5jhI',
    appId: '1:422614900421:web:2cc7557ce5cd0ef0679aac',
    messagingSenderId: '422614900421',
    projectId: 'crud-1a5f7',
    authDomain: 'crud-1a5f7.firebaseapp.com',
    storageBucket: 'crud-1a5f7.firebasestorage.app',
    measurementId: 'G-JR0528YBG0',
  );
}
